import argparse
import os
import sys
from typing import Any

import requests

DEFAULT_BASE_URL = os.getenv("LPI_BASE_URL", "http://localhost:3333")


def call_tool(base_url: str, endpoint: str, payload: dict[str, Any] | None = None) -> Any:
    payload = payload or {}

    try:
        response = requests.post(
            f"{base_url.rstrip('/')}/{endpoint}",
            json=payload,
            timeout=20,
        )
        response.raise_for_status()
        return response.json()

    except requests.exceptions.ConnectionError:
        print(f"[ERROR] Could not connect to {base_url}")
        print("Make sure the LPI sandbox/server is running and the URL is correct.")
        print("Example: python agent.py \"Explain digital twins\" --base-url http://localhost:3333")
        return None

    except requests.exceptions.Timeout:
        print(f"[ERROR] Request to '{endpoint}' timed out.")
        return None

    except requests.exceptions.HTTPError as e:
        print(f"[ERROR] HTTP error while calling '{endpoint}': {e}")
        try:
            print("Response body:")
            print(response.text)
        except Exception:
            pass
        return None

    except ValueError:
        print(f"[ERROR] '{endpoint}' did not return valid JSON.")
        try:
            print("Response body:")
            print(response.text)
        except Exception:
            pass
        return None


def format_output(title: str, data: Any) -> None:
    print(f"\n=== {title} ===")
    if isinstance(data, dict):
        for key, value in data.items():
            print(f"{key}: {value}")
    else:
        print(data)


def run_agent(user_query: str, base_url: str) -> int:
    print("\n=== LPI Explainable Agent ===")
    print(f"Question: {user_query}")
    print(f"Server:   {base_url}")

    knowledge = call_tool(base_url, "query_knowledge", {"query": user_query})
    insights = call_tool(
        base_url,
        "get_insights",
        {
            "scenario": user_query,
            "tier": "free",
        },
    )

    if knowledge is None or insights is None:
        print("\n[STOP] Agent could not complete because one or more tool calls failed.")
        return 1

    print("\n=== Agent Answer ===")
    print("This answer was generated by combining responses from multiple LPI tools.")

    format_output("query_knowledge response", knowledge)
    format_output("get_insights response", insights)

    print("\n=== Sources Used ===")
    print("- query_knowledge")
    print("- get_insights")

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Simple LPI agent that queries multiple tools and shows explainable output."
    )
    parser.add_argument(
        "query",
        nargs="?",
        default="Explain digital twins in simple terms",
        help="User question for the agent",
    )
    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help="Base URL of the running LPI server (default: http://localhost:3333 or LPI_BASE_URL env var)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    sys.exit(run_agent(args.query, args.base_url))
